Repository ginomessmer/mlsa-greenathon, pull requests merged in 2021-04, with the labels that each got.

#3 Create an action to check markdown links for blog
  .github/workflows/markdown-links.yml
Labels: enhancement

#2 Implement business submissions
  .github/workflows/azure-static-web-apps-brave-forest-079ba5803.yml
  .github/workflows/mlsa-greenathon-api.yml
  README.md
  api/MlsaGreenathon.Api/Data/IsoCountryCode.cs
  api/MlsaGreenathon.Api/Defaults.cs
  api/MlsaGreenathon.Api/Functions/Function1.cs
  api/MlsaGreenathon.Api/Functions/QueryBusinesses.cs
  api/MlsaGreenathon.Api/Functions/SubmitBusiness.cs
  api/MlsaGreenathon.Api/MappingProfile.cs
  api/MlsaGreenathon.Api/MlsaGreenathon.Api.csproj
  api/MlsaGreenathon.Api/Properties/Resources.Designer.cs
  api/MlsaGreenathon.Api/Properties/Resources.resx
  api/MlsaGreenathon.Api/Properties/ServiceDependencies/mlsa-greenathon/storage1.arm.json
  api/MlsaGreenathon.Api/Properties/serviceDependencies.mlsa-greenathon.json
  api/MlsaGreenathon.Api/Requests/CreateBusinessDto.cs
  api/MlsaGreenathon.Api/Requests/QueryBusinessDto.cs
  api/MlsaGreenathon.Api/Resources/Countries_Iso_3166-1.json
  api/MlsaGreenathon.Models/Business.cs
  api/MlsaGreenathon.Models/Entity.cs
  api/MlsaGreenathon.Models/MlsaGreenathon.Models.csproj
  api/MlsaGreenathon.sln
  docs/api.md
  docs/react.md
Labels: api, documentation

#4 Add UI style and components
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.jsx
  src/App.scss
  src/assets/icons/arrow_filter.svg
  src/components/SearchBox.jsx
  src/components/SearchBox.scss
  src/components/Sidebar.jsx
  src/components/Sidebar.scss
  src/components/index.js
  src/index.css
  src/index.js
  src/logo.svg
  src/styles/variables.scss
Labels: ui

#6 Implement business query function
  api/MlsaGreenathon.Api/Data/QueryBusinessParameters.cs
  api/MlsaGreenathon.Api/Database/BusinessRepository.cs
  api/MlsaGreenathon.Api/Functions/QueryBusinesses.cs
  api/MlsaGreenathon.Api/Requests/QueryBusinessDto.cs
Labels: api, enhancement

#11 Add some OSS docs
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
Labels: enhancement

#9 Implement modal
  package-lock.json
  package.json
  src/App.jsx
  src/App.scss
  src/assets/icons/close.svg
  src/assets/static/iso_countries.json
  src/components/ModalCloseButton.jsx
  src/components/ModalCloseButton.scss
  src/components/Sidebar.scss
  src/components/SubmitBusinessForm.tsx
  src/components/index.js
  src/react-app-env.d.ts
  src/services/api.ts
  tsconfig.json
Labels: enhancement, ui

#14 Feature/api geo position
  README.md
  api/MlsaGreenathon.Api/Functions/Function1.cs
  api/MlsaGreenathon.Api/Functions/SubmitBusiness.cs
  api/MlsaGreenathon.Api/MlsaGreenathon.Api.csproj
  api/MlsaGreenathon.Api/Startup.cs
  api/MlsaGreenathon.Models/Business.cs
Labels: api, enhancement

#16 Display map markers
  src/App.jsx
  src/components/SubmitBusinessForm.tsx
  src/services/api.ts
Labels: enhancement, ui

#18 MS Teams Flow Approval
  api/MlsaGreenathon.Api/Functions/ApproveBusiness.cs
  api/MlsaGreenathon.Api/Functions/SubmitBusiness.cs
  api/MlsaGreenathon.Models/Business.cs
  api/MlsaGreenathon.sln
  docs/ms-teams-approval_logic-app.md
Labels: api, enhancement

#21 UI Fixes
  package-lock.json
  package.json
  src/App.scss
  src/App.tsx
  src/components/SearchBox.scss
  src/data/BusinessMarker.ts
  src/data/index.ts
  src/index.css
  src/index.js
  src/services/api.ts
Labels: enhancement, ui
